### PR TITLE
Dev

### PR DESCRIPTION
**Pull request by Midgetking15**
Updated main.css and home.html

### CODE REVIEW

**Comment by Midgetking15** [comment]
I tried 120s , its a lot easier to read sponsor names now and doesn't cause difficulty to read. I grabbed colors from here https://brand.wisc.edu/web/colors/, creates a more decent UW-Theme I thought. I just think the font looks a little cartoony, was just trying out some different ones. Thought some harder text went better with some harder borders

**Comment by vkottler** [comment]
We should probably change our colors to some of the UW ones, I didn't know about that.

I agree the border-radius changes go better with that font but I still like the existing font. @jordanjones98 tie-breaker??

**Comment by jordanjones98** [comment]
I agree with @vkottler with the font, "Who we are" looks smaller than all of the other fonts, and it also takes up a good portion of the screen. It is also bigger than the header text. 

Slideshow may be a bit slow, but it does give people a chance to click on the sponsors website which is nice.

**Comment by vkottler** [comment]
The slower the slideshow is the less change a user has to see some of the sponsors later in the list. It probably is a bit too fast right now though

**Comment by Midgetking15** [comment]
I fixed the weird "Who we are" thing in a later build, should be pushed to dev

**Comment by Midgetking15** [comment]
Actually I made it too big, I'll bring it down a bit

**Comment by vkottler** [comment]
Let's do a new pull request without the border-radius changes and font changes

**Pull request closed without merging**
